config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new
    if @bookmark.save
      redirect_to list_bookmarks_path(@bookmark)
    else
      render 'new'
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  end

  def new
    @list = List.new
  end

  def show
    @list = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'bookmark/list'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/create.html.erb
<h1>Hello </h1>

  <%= simple_form_for (@list) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
  <% end %>

app/views/bookmarks/index.html.erb
<h1>My lists</h1>

<ul>
  <% @bookmark.each do |bookmark| %>
   <li><%= link_to bookmark.title, bookmark_path(bookmark) %></li>
   <% end %>
</ul>

<%= link_to "Add new list", list_bookmarks_path %>

app/views/bookmarks/new.html.erb
<%= simple_form_for(@list) do |f| %>
   <%= f.input :name %>
   <%= f.submit %>
 <% end %>


<%= link_to "Back to list", lists_path %>

app/views/bookmarks/show.html.erb
<h1>Watch list</h1>

 p><%= @bookmarks%></p>
 p><%= @lists%></p>

<% if @bookmark.completed %>
 ......
<% else %>
 .....
<% end %>

<hr>

<%= link_to "Back to list", bookmark_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My lists</h1>